'use client'
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { Booking, Service, photos, seedBookings, services as defaultServices, stylists } from '../lib/data'

type Store = {
  bookings: Booking[]; services: Service[];
  addBooking:(b:Booking)=>void; updateBooking:(id:string, patch:Partial<Booking>)=>void; updateService:(id:string, patch:Partial<Service>)=>void;
}
const StoreContext = createContext<Store | null>(null)
const KEY='morrow-demo-v1'

function StoreProvider({children}:{children:React.ReactNode}){
  const [bookings,setBookings]=useState<Booking[]>(seedBookings)
  const [serviceState,setServiceState]=useState<Service[]>(defaultServices)
  useEffect(()=>{
    try { const raw=sessionStorage.getItem(KEY); if(raw){const p=JSON.parse(raw); if(p.bookings)setBookings(p.bookings); if(p.services)setServiceState(p.services)} } catch{}
  },[])
  useEffect(()=>{ try{sessionStorage.setItem(KEY,JSON.stringify({bookings,services:serviceState}))}catch{} },[bookings,serviceState])
  const value=useMemo<Store>(()=>({
    bookings, services:serviceState,
    addBooking:b=>setBookings(x=>[...x,b]),
    updateBooking:(id,patch)=>setBookings(x=>x.map(b=>b.id===id?{...b,...patch}:b)),
    updateService:(id,patch)=>setServiceState(x=>x.map(s=>s.id===id?{...s,...patch}:s))
  }),[bookings,serviceState])
  return <StoreContext.Provider value={value}>{children}</StoreContext.Provider>
}
function useStore(){const s=useContext(StoreContext); if(!s)throw new Error('store'); return s}

function go(router:any,path:string){router.push(path)}
function Button({children,onClick,variant='solid',type='button'}:{children:React.ReactNode,onClick?:()=>void,variant?:'solid'|'ghost'|'light',type?:'button'|'submit'}){
  return <button type={type} onClick={onClick} className={`btn btn-${variant}`}>{children}</button>
}
function DemoBar(){return <div className="demo-bar"><span><b>ORVIA WEB DEMONSTRATION</b> — A working concept created to show what ORVIA Web can build.</span><span><a href="https://web.orvia.org.uk/start?demo=business">BUILD SOMETHING LIKE THIS</a><a href="https://web.orvia.org.uk/">VIEW ORVIA WEB</a></span></div>}
function Header(){
  const r=useRouter(); const [open,setOpen]=useState(false)
  const links=[['ABOUT','/about'],['SERVICES','/services'],['STUDIO','/#studio'],['REVIEWS','/reviews'],['BOOK','/book'],['CONTACT','/contact']]
  return <><DemoBar/><header><button className="brand" onClick={()=>go(r,'/')}>MORROW STUDIO</button><nav className={open?'open':''}>{links.map(([n,p])=><button key={n} onClick={()=>{setOpen(false);go(r,p)}}>{n}</button>)}<Button onClick={()=>go(r,'/book')}>BOOK AN APPOINTMENT</Button></nav><button className="menu" aria-label="Open menu" onClick={()=>setOpen(!open)}>MENU</button></header></>
}
function Footer(){return <footer><div><div className="footer-brand">MORROW STUDIO</div><p>Sheffield · Demonstration location</p><p className="muted">Fictional ORVIA Web concept. No real salon, appointments or payments.</p></div><div><a href="/demo-information">DEMO INFORMATION</a><a href="https://web.orvia.org.uk/start?demo=business">BUILD SOMETHING LIKE THIS</a><a href="https://web.orvia.org.uk/">ORVIA WEB</a></div></footer>}
function Shell({children,desk=false}:{children:React.ReactNode,desk?:boolean}){return <div className={desk?'desk-shell':''}>{!desk&&<Header/>}{children}{!desk&&<Footer/>}</div>}
function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow">{children}</div>}
function Picture({src,alt,className='' }:{src:string,alt:string,className?:string}){return <img className={className} src={src} alt={alt} loading="lazy"/>}

function Home(){const r=useRouter(); const {services}=useStore(); return <Shell>
  <main>
    <section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(20,18,16,.62),rgba(20,18,16,.12)),url('${photos.hero}')`}}>
      <div className="hero-copy"><Eyebrow>INDEPENDENT HAIR STUDIO · SHEFFIELD</Eyebrow><h1>GOOD HAIR.<br/>PROPERLY CONSIDERED.</h1><p>Cutting, colour and styling in a calm Sheffield studio where appointments are given the time they actually need.</p><div className="row"><Button onClick={()=>go(r,'/book')}>BOOK AN APPOINTMENT</Button><Button variant="light" onClick={()=>go(r,'/services')}>EXPLORE SERVICES</Button></div><small>CUTTING · COLOUR · STYLING</small></div>
    </section>
    <section className="split intro"><div><Eyebrow>THE MORROW APPROACH</Eyebrow><h2>NO RUSH.<br/>NO CONVEYOR BELT.</h2><p>Morrow is designed around appointments that leave enough time to listen, work properly and finish well.</p><p>Whether you’re coming in for a straightforward cut or a bigger colour change, the process starts with understanding what you want — and what will actually work for your hair.</p></div><Picture src={photos.client} alt="A calm salon consultation"/></section>
    <section className="section services-preview"><div className="section-head"><div><Eyebrow>SERVICES</Eyebrow><h2>WHAT CAN WE DO FOR YOU?</h2></div><p>Demonstration prices. Every service can be selected directly into the booking flow.</p></div><div className="service-list">{services.map(s=><article key={s.id}><div><h3>{s.name}</h3><p>{s.blurb}</p></div><div className="service-meta"><span>{s.duration} MIN</span><b>{s.price}</b><button onClick={()=>go(r,`/book?service=${s.id}`)}>BOOK THIS SERVICE →</button></div></article>)}</div></section>
    <section id="studio" className="studio-feature"><Picture src={photos.interior} alt="Morrow Studio demonstration interior"/><div className="studio-card"><Eyebrow>THE STUDIO</Eyebrow><h2>A STUDIO DESIGNED<br/>TO FEEL CALM.</h2><p>Good work is easier when nobody feels rushed. Morrow is designed around considered appointments, warm light, natural materials and enough time to do the job properly.</p><Button onClick={()=>go(r,'/about')}>ABOUT MORROW</Button></div></section>
    <section className="section team"><div className="section-head"><div><Eyebrow>THE TEAM</Eyebrow><h2>THREE DIFFERENT WAYS OF WORKING WELL.</h2></div><p>Fictional demonstration profiles. No real qualifications are claimed.</p></div>{stylists.map((s,i)=><article className="team-row" key={s.id}><span>0{i+1}</span><div><h3>{s.name}</h3><p>{s.role}</p></div><ul>{s.specialties.map(x=><li key={x}>{x}</li>)}</ul></article>)}</section>
    <section className="gallery"><div className="g1"><Picture src={photos.stylist} alt="Stylist working"/></div><div className="g2"><Picture src={photos.detail} alt="Salon detail"/></div><div className="g3"><Picture src={photos.finished} alt="Finished hair styling"/></div><div className="g4"><Picture src={photos.tools} alt="Hair styling tools"/></div></section>
    <section className="booking-story split"><Picture src={photos.phone} alt="Customer booking from a phone"/><div><Eyebrow>ONLINE BOOKING</Eyebrow><h2>BOOK WHEN<br/>IT SUITS YOU.</h2><p>Choose your service, your stylist and an available appointment without waiting for someone to answer the phone.</p><Button onClick={()=>go(r,'/book')}>BOOK AN APPOINTMENT</Button><div className="statement">YOUR CUSTOMER BOOKS ONLINE.<br/>THE APPOINTMENT APPEARS IN YOUR WORKSPACE.</div></div></section>
    <VideoSection/>
    <section className="section reviews-tease"><Eyebrow>REVIEWS</Eyebrow><h2>WHAT A CUSTOMER REVIEW SECTION<br/>COULD LOOK LIKE.</h2><div className="quotes">{[
      'The whole appointment felt considered from start to finish. I never felt rushed and I left understanding how to look after the cut properly.',
      'Really clear consultation before we started. The colour feels like me rather than something copied from a photograph.',
      'Beautiful studio, relaxed atmosphere and genuinely straightforward advice.'
    ].map((q,i)=><blockquote key={i}><small>FICTIONAL DEMONSTRATION REVIEW</small><p>“{q}”</p></blockquote>)}</div><Button variant="ghost" onClick={()=>go(r,'/reviews')}>VIEW REVIEW DEMO</Button></section>
    <section className="split owner-story"><div><Eyebrow>MORE THAN A WEBSITE</Eyebrow><h2>YOUR WEBSITE TAKES THE BOOKING.<br/>YOUR WORKSPACE TAKES IT FROM THERE.</h2><p>Morrow demonstrates how an ORVIA Web build can connect the customer-facing website to a simple business tool behind it.</p><div className="feature-grid">{['ONLINE BOOKINGS','TODAY’S APPOINTMENTS','CUSTOMER RECORDS','SERVICES','AVAILABILITY','MESSAGES'].map(x=><span key={x}>{x}</span>)}</div><Button onClick={()=>go(r,'/book')}>TRY THE BOOKING DEMO</Button></div><Picture src={photos.owner} alt="Small business owner using a laptop"/></section>
    <section className="closing"><Eyebrow>BUILT BY ORVIA WEB</Eyebrow><h2>YOUR WEBSITE CAN TAKE BOOKINGS<br/>WHILE YOU’RE BUSY WITH CUSTOMERS.</h2><p>Public website outside. Practical business tool behind it.</p><div className="row"><a className="btn btn-solid" href="https://web.orvia.org.uk/start?demo=business">BUILD SOMETHING LIKE THIS</a><a className="btn btn-ghost" href="https://web.orvia.org.uk/">VIEW ORVIA WEB</a></div><div className="closing-line">YOU RUN THE BUSINESS.<br/>WE’LL TAKE CARE OF THE WEB.</div></section>
  </main>
</Shell>}

function VideoSection(){return <section className="section video-section"><div><Eyebrow>FROM BOOKING TO THE DIARY</Eyebrow><h2>YOUR CUSTOMER BOOKS.<br/>YOUR DAY UPDATES.</h2><p>A website can do more than tell people what you offer. With ORVIA Web, customers can choose a service, book a time and send the information straight into the business workspace behind the website.</p></div><div className="video-frame"><video autoPlay muted loop playsInline controls preload="metadata" poster={photos.phone} aria-label="Morrow Studio ORVIA Web showcase film"><source src="https://raw.githubusercontent.com/ORVIA-Oversight/orvia-web-showcase/main/Create_a_second_cinematic_p%20(2).mp4" type="video/mp4"/>Your browser does not support video playback.</video></div></section>}

function About(){const r=useRouter();return <Shell><main><section className="page-hero"><Eyebrow>ABOUT MORROW</Eyebrow><h1>A SMALL STUDIO<br/>WITH TIME TO DO THINGS PROPERLY.</h1></section><section className="split"><Picture src={photos.interior2} alt="Salon interior"/><div><h2>CONSIDERED FROM THE START.</h2><p>Morrow is a fictional independent Sheffield hair studio built to demonstrate a different kind of small-business website: visually strong on the outside, genuinely useful behind it.</p><p>The appointment experience is based around time, listening and realistic advice rather than pressure, overbooking or a conveyor-belt feel.</p></div></section><section className="split reverse"><Picture src={photos.client} alt="Stylist consultation"/><div><Eyebrow>CONSULTATION</Eyebrow><h2>START WITH WHAT WILL ACTUALLY WORK.</h2><p>Every service begins with context: how you wear your hair, what you are prepared to maintain, what has worked before and what has not.</p><Button onClick={()=>go(r,'/book')}>BOOK A DEMO APPOINTMENT</Button></div></section><section className="section"><Picture className="wide-image" src={photos.stylist} alt="Stylist at work"/></section></main></Shell>}

function ServicesPage(){const r=useRouter();const {services}=useStore();return <Shell><main><section className="page-hero"><Eyebrow>SERVICES</Eyebrow><h1>ENOUGH TIME<br/>TO DO IT PROPERLY.</h1><p>All prices and services are demonstration content.</p></section><section className="section service-detail-list">{services.map((s,i)=><article key={s.id}><div className="num">0{i+1}</div><div><h2>{s.name}</h2><p>{s.blurb}</p><p className="muted"><b>WHO IT SUITS:</b> {s.suits}</p></div><div className="service-meta"><span>{s.duration} MIN</span><b>{s.price}</b><Button onClick={()=>go(r,`/book?service=${s.id}`)}>BOOK THIS SERVICE</Button></div></article>)}</section></main></Shell>}

function Reviews(){return <Shell><main><section className="page-hero"><Eyebrow>REVIEWS</Eyebrow><h1>FEEDBACK,<br/>WITHOUT THE FAKE BADGES.</h1><p>This page demonstrates how customer feedback could be presented on a completed ORVIA Web website.</p></section><section className="section editorial-reviews">{[
  ['The whole appointment felt considered from start to finish.','I never felt rushed and I left understanding how to look after the cut properly.'],
  ['Really clear consultation before we started.','The colour feels like me rather than something copied from a photograph.'],
  ['Beautiful studio, relaxed atmosphere.','Genuinely straightforward advice and enough time to make the appointment feel calm.']
].map((x,i)=><article key={i}><span>FICTIONAL DEMONSTRATION REVIEW</span><h2>“{x[0]}”</h2><p>{x[1]}</p></article>)}</section></main></Shell>}

function BookingFlow(){
  const r=useRouter(), q=useSearchParams(); const store=useStore();
  const initial=q.get('service')||''
  const [step,setStep]=useState(1); const [done,setDone]=useState<Booking|null>(null)
  const [data,setData]=useState({serviceId:initial,stylistId:'any',date:'',time:'',first:'',last:'',email:'',phone:'',firstVisit:true,notes:''})
  const availableServices=store.services.filter(s=>s.active)
  const days=Array.from({length:10},(_,i)=>{const d=new Date(); d.setDate(d.getDate()+i+1); return d.toISOString().slice(0,10)})
  const times=['09:00','10:15','11:30','13:00','14:30','16:00','17:15']
  const selectedService=store.services.find(s=>s.id===data.serviceId)
  const selectedStylist=data.stylistId==='any'?null:stylists.find(s=>s.id===data.stylistId)
  function next(){setStep(Math.min(6,step+1))}
  function back(){setStep(Math.max(1,step-1))}
  function submit(){
    if(!selectedService||!data.date||!data.time||!data.first||!data.last||!data.email||!data.phone)return
    const assigned=data.stylistId==='any'?stylists[Math.floor(Math.random()*stylists.length)].id:data.stylistId
    const b:Booking={id:`user-${Date.now()}`,ref:`MOR-DEMO-${String(Date.now()).slice(-4)}`,serviceId:data.serviceId,stylistId:assigned,date:data.date,time:data.time,first:data.first,last:data.last,email:data.email,phone:data.phone,firstVisit:data.firstVisit,notes:data.notes,status:'booked',createdAt:Date.now()}
    store.addBooking(b); setDone(b)
  }
  if(done){const s=store.services.find(x=>x.id===done.serviceId), st=stylists.find(x=>x.id===done.stylistId);return <Shell><main className="booking-page"><section className="success"><Eyebrow>BOOKING COMPLETE</Eyebrow><h1>YOU’RE BOOKED.</h1><p>This is a demonstration appointment. No fictional salon has received your booking.</p><div className="receipt"><b>{done.ref}</b><span>{s?.name}</span><span>{st?.name}</span><span>{done.date} · {done.time}</span></div><Button onClick={()=>go(r,'/desk/today')}>VIEW IT IN THE OWNER APP</Button></section></main></Shell>}
  return <Shell><main className="booking-page"><section className="booking-wrap"><div className="progress"><span>{step} OF 6</span><div><i style={{width:`${step/6*100}%`}}/></div></div>
    {step===1&&<div className="booking-step"><Eyebrow>CHOOSE YOUR SERVICE</Eyebrow><h1>WHAT ARE WE DOING?</h1><div className="choice-list">{availableServices.map(s=><button className={data.serviceId===s.id?'selected':''} key={s.id} onClick={()=>setData({...data,serviceId:s.id})}><span><b>{s.name}</b><small>{s.blurb}</small></span><span>{s.duration} MIN<br/><b>{s.price}</b></span></button>)}</div></div>}
    {step===2&&<div className="booking-step"><Eyebrow>WHO WOULD YOU LIKE TO SEE?</Eyebrow><h1>CHOOSE A STYLIST.</h1><div className="choice-list">{[{id:'any',name:'ANY AVAILABLE STYLIST',role:'We’ll assign an available stylist.'},...stylists].map((s:any)=><button className={data.stylistId===s.id?'selected':''} key={s.id} onClick={()=>setData({...data,stylistId:s.id})}><span><b>{s.name}</b><small>{s.role}</small></span><span>SELECT →</span></button>)}</div></div>}
    {step===3&&<div className="booking-step"><Eyebrow>CHOOSE A DATE</Eyebrow><h1>WHEN SUITS YOU?</h1><div className="date-grid">{days.map(d=><button className={data.date===d?'selected':''} key={d} onClick={()=>setData({...data,date:d})}><small>{new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})}</small><b>{new Date(d+'T12:00:00').getDate()}</b><span>{new Date(d+'T12:00:00').toLocaleDateString('en-GB',{month:'short'})}</span></button>)}</div></div>}
    {step===4&&<div className="booking-step"><Eyebrow>CHOOSE A TIME</Eyebrow><h1>AVAILABLE APPOINTMENTS.</h1><div className="time-grid">{times.map((t,i)=><button disabled={i===2||i===5} className={data.time===t?'selected':''} key={t} onClick={()=>setData({...data,time:t})}>{t}{(i===2||i===5)&&<small>UNAVAILABLE</small>}</button>)}</div></div>}
    {step===5&&<div className="booking-step"><Eyebrow>YOUR DETAILS</Eyebrow><h1>WHO’S COMING IN?</h1><div className="notice">ORVIA WEB DEMONSTRATION — PLEASE DO NOT ENTER SENSITIVE OR CONFIDENTIAL INFORMATION.</div><div className="form-grid"><label>First name *<input value={data.first} onChange={e=>setData({...data,first:e.target.value})}/></label><label>Last name *<input value={data.last} onChange={e=>setData({...data,last:e.target.value})}/></label><label>Email *<input type="email" value={data.email} onChange={e=>setData({...data,email:e.target.value})}/></label><label>Phone *<input value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><label className="full">First visit?<select value={data.firstVisit?'yes':'no'} onChange={e=>setData({...data,firstVisit:e.target.value==='yes'})}><option value="yes">YES</option><option value="no">NO</option></select></label><label className="full">General notes — optional<textarea value={data.notes} onChange={e=>setData({...data,notes:e.target.value})}/></label></div></div>}
    {step===6&&<div className="booking-step"><Eyebrow>CONFIRM YOUR APPOINTMENT</Eyebrow><h1>CHECK THE DETAILS.</h1><div className="summary"><div><span>SERVICE</span><b>{selectedService?.name}</b></div><div><span>STYLIST</span><b>{selectedStylist?.name||'ANY AVAILABLE STYLIST'}</b></div><div><span>DATE</span><b>{data.date}</b></div><div><span>TIME</span><b>{data.time}</b></div><div><span>DURATION</span><b>{selectedService?.duration} MINUTES</b></div><div><span>DEMO PRICE</span><b>{selectedService?.price}</b></div></div><div className="notice"><b>DEMONSTRATION CHECKOUT</b><br/>NO REAL PAYMENT WILL BE TAKEN.</div><div className="row"><Button onClick={submit}>BOOK DEMONSTRATION APPOINTMENT</Button><Button variant="ghost" onClick={submit}>£10 TEST DEPOSIT</Button></div></div>}
    <div className="booking-actions">{step>1?<Button variant="ghost" onClick={back}>BACK</Button>:<span/>}{step<6&&<Button onClick={next}>CONTINUE</Button>}</div>
  </section></main></Shell>
}

function DeskLayout({children}:{children:React.ReactNode}){const r=useRouter(),p=usePathname(); const items=[['TODAY','/desk/today'],['BOOKINGS','/desk/bookings'],['CUSTOMERS','/desk/customers'],['SERVICES','/desk/services'],['AVAILABILITY','/desk/availability'],['MESSAGES','/desk/messages']];return <Shell desk><div className="desk"><aside><button className="desk-brand" onClick={()=>go(r,'/desk/today')}>MORROW DESK<small>ORVIA WEB DEMO</small></button><nav>{items.map(([n,path])=><button className={p===path?'active':''} key={path} onClick={()=>go(r,path)}>{n}</button>)}</nav><Button variant="ghost" onClick={()=>go(r,'/')}>VIEW PUBLIC WEBSITE</Button></aside><div className="desk-main">{children}</div><nav className="desk-bottom">{items.slice(0,3).map(([n,path])=><button className={p===path?'active':''} key={path} onClick={()=>go(r,path)}>{n}</button>)}<button onClick={()=>go(r,'/desk/services')}>MORE</button></nav></div></Shell>}
function todayKey(){return new Date().toISOString().slice(0,10)}
function sortBookings(bs:Booking[]){return [...bs].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
function DeskToday(){const store=useStore(); const [move,setMove]=useState<Booking|null>(null); const today=todayKey(); const list=sortBookings(store.bookings.filter(b=>b.date==='TODAY'||b.date===today)); return <DeskLayout><DeskHead title="TODAY" subtitle="Your working diary — demonstration records only."/><div className="desk-list">{list.map(b=><BookingRow key={b.id} booking={b} onMove={()=>setMove(b)}/>)}</div>{move&&<MoveModal booking={move} close={()=>setMove(null)}/>}</DeskLayout>}
function DeskHead({title,subtitle}:{title:string,subtitle:string}){return <div className="desk-head"><div><Eyebrow>MORROW STUDIO</Eyebrow><h1>{title}</h1><p>{subtitle}</p></div><div className="desk-date">{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}).toUpperCase()}</div></div>}
function BookingRow({booking,onMove}:{booking:Booking,onMove:()=>void}){const store=useStore(); const s=store.services.find(x=>x.id===booking.serviceId), st=stylists.find(x=>x.id===booking.stylistId);return <article className="booking-row"><div className="time">{booking.time}</div><div><h3>{booking.first} {booking.last}</h3><p>{st?.name} · {s?.name}</p><small>{booking.ref} · {booking.status.toUpperCase()}</small></div><div className="row-actions"><button onClick={()=>store.updateBooking(booking.id,{status:'checked-in'})}>CHECK IN</button><button onClick={onMove}>MOVE</button><button onClick={()=>alert('Demonstration only — no real message sent.')}>MESSAGE</button><button onClick={()=>store.updateBooking(booking.id,{status:'complete'})}>COMPLETE</button></div></article>}
function MoveModal({booking,close}:{booking:Booking,close:()=>void}){const store=useStore();const [date,setDate]=useState(booking.date==='TODAY'?todayKey():booking.date);const [time,setTime]=useState(booking.time);return <div className="modal-backdrop"><div className="modal"><Eyebrow>MOVE / RESCHEDULE</Eyebrow><h2>{booking.first} {booking.last}</h2><label>New date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>New time<select value={time} onChange={e=>setTime(e.target.value)}>{['09:00','10:15','11:30','13:00','14:30','16:00','17:15'].map(t=><option key={t}>{t}</option>)}</select></label><div className="row"><Button onClick={()=>{store.updateBooking(booking.id,{date,time});alert('APPOINTMENT UPDATED — DEMONSTRATION');close()}}>UPDATE APPOINTMENT</Button><Button variant="ghost" onClick={close}>CANCEL</Button></div></div></div>}
function DeskBookings(){const store=useStore();const [move,setMove]=useState<Booking|null>(null);return <DeskLayout><DeskHead title="BOOKINGS" subtitle="Today, week and upcoming in one clean list."/><div className="tabs"><button className="active">TODAY</button><button>WEEK</button><button>UPCOMING</button></div><div className="desk-list">{sortBookings(store.bookings).map(b=><BookingRow key={b.id} booking={b} onMove={()=>setMove(b)}/>)}</div>{move&&<MoveModal booking={move} close={()=>setMove(null)}/>}</DeskLayout>}
function DeskCustomers(){const store=useStore();const users=store.bookings.filter(b=>!b.id.startsWith('seed-'));const all=[...seedBookings,...users];return <DeskLayout><DeskHead title="CUSTOMERS" subtitle="Fictional demo customer records only. No sensitive data."/><div className="customer-grid">{all.map(b=><article key={b.id}><span>{b.first[0]}{b.last[0]}</span><div><h3>{b.first} {b.last}</h3><p>Preferred stylist: {stylists.find(x=>x.id===b.stylistId)?.name}</p><small>Next booking: {b.date} · {b.time}</small></div></article>)}</div></DeskLayout>}
function DeskServices(){const store=useStore();return <DeskLayout><DeskHead title="SERVICES" subtitle="Turn services on or off and change demonstration pricing and duration."/><div className="manage-list">{store.services.map(s=><article key={s.id}><div><h3>{s.name}</h3><p>{s.blurb}</p></div><label>Active<input type="checkbox" checked={s.active} onChange={e=>store.updateService(s.id,{active:e.target.checked})}/></label><label>Duration<input type="number" value={s.duration} onChange={e=>store.updateService(s.id,{duration:Number(e.target.value)})}/></label><label>Demo price<input value={s.price} onChange={e=>store.updateService(s.id,{price:e.target.value})}/></label></article>)}</div></DeskLayout>}
function DeskAvailability(){const [days,setDays]=useState(['TUE','WED','THU','FRI','SAT']);return <DeskLayout><DeskHead title="AVAILABILITY" subtitle="A lightweight demonstration of working hours and blocked time."/><section className="availability"><h2>OPENING DAYS</h2><div className="day-toggles">{['MON','TUE','WED','THU','FRI','SAT','SUN'].map(d=><button key={d} className={days.includes(d)?'active':''} onClick={()=>setDays(x=>x.includes(d)?x.filter(y=>y!==d):[...x,d])}>{d}</button>)}</div><div className="form-grid"><label>Opening time<input type="time" defaultValue="09:00"/></label><label>Closing time<input type="time" defaultValue="18:00"/></label><label className="full">Block time<input type="text" defaultValue="Thursday 13:00–14:00"/></label></div><Button onClick={()=>alert('Availability updated — demonstration only.')}>SAVE DEMO AVAILABILITY</Button></section></DeskLayout>}
function DeskMessages(){const [msgs,setMsgs]=useState([{id:1,t:'BOOKING QUESTION',n:'Could I move my demo appointment by 30 minutes?',s:'NEW'},{id:2,t:'COLOUR CONSULTATION',n:'I would like to know how the consultation works.',s:'NEW'},{id:3,t:'GENERAL ENQUIRY',n:'Do you offer styling appointments?',s:'RESPONDED'}]);return <DeskLayout><DeskHead title="MESSAGES" subtitle="No genuine external messages are sent from this demonstration."/><div className="messages">{msgs.map(m=><article key={m.id}><div><Eyebrow>{m.t}</Eyebrow><p>{m.n}</p><small>{m.s}</small></div><div><button onClick={()=>alert(m.n)}>VIEW</button><button onClick={()=>setMsgs(x=>x.map(y=>y.id===m.id?{...y,s:'RESPONDED'}:y))}>MARK RESPONDED</button><button onClick={()=>setMsgs(x=>x.filter(y=>y.id!==m.id))}>ARCHIVE</button></div></article>)}</div></DeskLayout>}

function Contact(){return <Shell><main><section className="page-hero"><Eyebrow>CONTACT</Eyebrow><h1>SHEFFIELD<br/>DEMONSTRATION LOCATION.</h1><p>Morrow Studio is fictional. No actual salon street address exists for this concept.</p></section><section className="section contact-panel"><div><h2>MORROW IS AN ORVIA WEB CONCEPT DEMONSTRATION.</h2><p>It exists to show how a premium independent-business website can connect to online booking and a practical owner workspace.</p></div><a className="btn btn-solid" href="https://web.orvia.org.uk/start?demo=business">BUILD SOMETHING LIKE THIS</a></section></main></Shell>}
function DemoInfo(){return <Shell><main><section className="page-hero"><Eyebrow>DEMO INFORMATION</Eyebrow><h1>THIS IS A WORKING CONCEPT.<br/>NOT A REAL SALON.</h1></section><section className="section legal-copy"><p>Morrow Studio is fictional. Team members are fictional. Reviews are fictional demonstration content. Prices are demonstration prices. No real appointments are created outside this browser session. No fictional salon receives submissions. No real payment is taken. Images are licensed demonstration imagery. The site exists to demonstrate ORVIA Web capabilities.</p></section></main></Shell>}
function NotFound(){const r=useRouter();return <Shell><main><section className="notfound"><Eyebrow>404</Eyebrow><h1>THAT APPOINTMENT<br/>ISN’T HERE.</h1><div className="row"><Button onClick={()=>go(r,'/book')}>BOOK AN APPOINTMENT</Button><Button variant="ghost" onClick={()=>go(r,'/')}>RETURN HOME</Button><a className="btn btn-ghost" href="https://web.orvia.org.uk/">VIEW ORVIA WEB</a></div></section></main></Shell>}

function RouterView(){const p=usePathname();if(p==='/')return <Home/>;if(p==='/about')return <About/>;if(p==='/services')return <ServicesPage/>;if(p==='/reviews')return <Reviews/>;if(p==='/book')return <BookingFlow/>;if(p==='/contact')return <Contact/>;if(p==='/demo-information')return <DemoInfo/>;if(p==='/desk'||p==='/desk/today')return <DeskToday/>;if(p==='/desk/bookings')return <DeskBookings/>;if(p==='/desk/customers')return <DeskCustomers/>;if(p==='/desk/services')return <DeskServices/>;if(p==='/desk/availability')return <DeskAvailability/>;if(p==='/desk/messages')return <DeskMessages/>;return <NotFound/>}
export default function MorrowApp(){return <StoreProvider><RouterView/></StoreProvider>}
